Repository fourkie/fourkie, pull requests merged in 2025-04, with the labels that each got.

#13 [Feature/Home] 데이터 가져오기 로직 추가 이미지 로직 추가 #3
  next.config.mjs
  src/app/(home)/components/home-diary.tsx
  src/app/(home)/types/HomePost.ts
  src/app/page.tsx
  src/constants/emotions-url.ts
  src/services/home-services.ts
  src/utils/home-emotion.util.ts
Labels: 🐰 선영, ✨ Feature

#22 [Feature/Component] 공통 이미지 컴포넌트 #21
  src/_components/common-emotion-image.tsx
  src/_components/types/ImgComponent.type.ts
  src/app/(home)/components/home-diary.tsx
Labels: 🐰 선영, ✨ Feature

#20 [Feature/Mypage] 회원가입 시 닉네임 추가, supabase 테이블에 연동 #10
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/app/sign-up/type.ts
  src/constants/form-message.ts
  src/services/auth-services.ts
Labels: 🐞 BugFix, 🧸 주하, 🪫 도현, ✨ Feature

#15 [Refactor/SignUp,SignIn] supabase 로직 변경 #10
  src/services/supabase-server.ts
  src/services/supabase.ts
Labels: 🔨 Refactor, 🐋 현식

#27 [bugfix/SignUp,SignIn] 유저 데이터가 안뜨는 버그 수정
  src/services/auth-services.ts
  src/services/home-services.ts
  src/services/supabase-client.ts
  src/services/supabase-server.ts
  src/services/supabase.ts
Labels: 🐞 BugFix, 🐋 현식

#24 [add] supabase type 추가
  database.types.ts
  package.json
Labels: 🐰 선영, ✨ Feature

#29 [Feature/component] 버튼 컴포넌트 추가
  src/types/common-components.types.ts
  src/ui/common/button.tsx
Labels: 🧸 주하, ✨ Feature, 🎨 CSS

#14 [Feature/List] 컴포넌트 추가 #5
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/list/page.tsx
  src/hooks/queries/use-get-all-posts-query.ts
  src/hooks/queries/use-get-user-by-id-query.ts
  src/services/post-services.ts
  src/services/user-services.ts
  src/types/posts.types.ts
Labels: 🧸 주하, ✨ Feature, 🎨 CSS

#30 [Feature/Home] 홈페이지 기능 업데이트 #3
  src/_components/common-emotion-image.tsx
  src/app/(home)/components/home-diary.tsx
  src/app/(home)/components/home-nopost.tsx
  src/constants/toast-message.ts
  src/services/home-services.ts
Labels: 🐰 선영, ✨ Feature

#32 [Feature/Home] date picker 반영 #3
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-diary.tsx
  src/app/page.tsx
Labels: 🐰 선영, ✨ Feature

#33 [Feature/Music] Spotify 인증 및 토큰 갱신 로직 구현 및 에러 메시지 정리 #4
  package.json
  pnpm-lock.yaml
  src/app/api/spotify/callback/route.ts
  src/app/api/spotify/login/route.ts
  src/app/api/spotify/token/route.ts
  src/constants/spotify.ts
  src/constants/toast-message.ts
Labels: 🐥 우영, ✨ Feature

#35 [Feature/Posting] 텍스트를 통한 감정 뽑아내기
  src/app/api/posting/route.ts
  src/app/layout.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/constants/ai.ts
  src/constants/form-message.ts
  src/constants/toast-message.ts
  src/hooks/mutations/use-post-emotion-mutation.ts
  src/services/posting-services.ts
Labels: ✨ Feature, 🐋 현식

#37 [Feature/List] 친구 게시물 / 내 게시물 조건부 렌더링
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/list/page.tsx
  src/hooks/queries/use-get-all-posts-query.ts
  src/hooks/queries/use-get-friend-posts-query.ts
  src/hooks/queries/use-get-my-posts-query.ts
  src/services/friend-services.ts
  src/services/post-services.ts
  src/services/user-services.ts
Labels: 🧸 주하, ✨ Feature

#38 [Feature/Home] 달력을 구현하고 유저의 이미지를 넣어봤습니다.
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-diary.tsx
  src/app/page.tsx
  src/services/home-client.ts
  src/services/home-services.ts
Labels: 🐰 선영, ✨ Feature

#39 [Refactor/Posting] 파일 분리
  src/app/api/posting/route.ts
  src/app/posting/_components/posting-form.tsx
  src/app/posting/_components/posting-result-modal.tsx
  src/app/posting/type.ts
  src/hooks/mutations/use-post-emotion-mutation.ts
  src/services/posting-services.ts
Labels: 🔨 Refactor, 🐋 현식

#40 [Feature/music] 로그아웃 처리 및 토큰 만료 로직 개선 #4
  src/app/api/spotify/callback/route.ts
  src/app/api/spotify/logout/route.ts
  src/app/api/spotify/token/route.ts
  src/constants/spotify.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature

#41 [Feature/component] Navigation 기본 기능
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
Labels: 🧸 주하, ✨ Feature

#44 [Feature/mypage] 회원가입/로그인 유효성 검사 / 리팩토링
  src/app/(layout)/header.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-in/type.ts
  src/app/sign-up/_components/sign-up-form.tsx
  src/constants/form-message.ts
  src/constants/validations.constant.ts
  src/services/auth-services.ts
Labels: 🔨 Refactor, 🪫 도현, ✨ Feature

#43 [Feature/Home] 달력과 데이트피커 연결
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/types/HomeDate.ts
  src/app/page.tsx
  src/constants/query-data.ts
  src/hooks/queries/use-get-user-posts-by-month-query.ts
Labels: 🐰 선영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#45 [Setting] 기본 컬러 세팅
  src/app/globals.css
  tailwind.config.ts
Labels: ⚙️ Setting, 🧸 주하, 🎨 CSS

#46 [Feature/posting] 감정 분석 로딩창 개선 및 닉네임 삽입 #8
  package.json
  pnpm-lock.yaml
  src/app/posting/_components/posting-form.tsx
  src/app/posting/_components/posting-result-modal.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/hooks/mutations/use-post-emotion-mutation.ts
  src/services/posting-services.ts
Labels: ⚙️ Setting, ✨ Feature, 🐋 현식, 🎨 CSS

#47 [Feature/Homeheader] 상단에 닉네임 헤더와 작성 버튼 추가 및 코드 리펙토링 #3
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-header.tsx
  src/app/page.tsx
  src/services/home-services.ts
Labels: 🐰 선영, 🔨 Refactor, ✨ Feature

#51 [Setting] 컬러 변경
  src/app/(layout)/navigation.tsx
  src/app/globals.css
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  tailwind.config.ts
Labels: ⚙️ Setting, 🧸 주하, 🎨 CSS

#48 [Feature/posting] 감정 분석 결과 모달창 기능 추가#8
  src/app/api/posting/route.ts
  src/app/posting/_components/posting-form.tsx
  src/app/posting/_components/posting-result-modal.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/services/posting-services.ts
Labels: 🐞 BugFix, ✨ Feature, 🐋 현식

#54 [Feature/mypage] 불필요한 파일명 정리, 공통 컴포넌트, 쿠키 이모지 추가 등
  src/app/(home)/components/home-calendar.tsx
  src/app/(layout)/header.tsx
  src/app/api/posting/route.ts
  src/app/api/spotify/callback/route.ts
  src/app/api/spotify/login/route.ts
  src/app/api/spotify/logout/route.ts
  src/app/api/spotify/token/route.ts
  src/app/list/_components/list-card.tsx
  src/app/list/page.tsx
  src/app/music/components/music-spotify.tsx
  src/app/page.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/constants/ai.constant.ts
  src/constants/emotion.constant.ts
  src/constants/emotions-url.constant.ts
  src/constants/emotions-url.ts
  src/constants/env.ts
  src/constants/form-message.constant.ts
  src/constants/query-data.constant.ts
  src/constants/query-keys.constant.ts
  src/constants/spotify.constant.ts
  src/constants/toast-message.constant.ts
  src/constants/validations.constant.ts
  src/hooks/mutations/auth-mutation.ts
  src/hooks/mutations/use-post-emotion-mutation.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/hooks/queries/use-get-all-posts-query.ts
  src/hooks/queries/use-get-friend-posts-query.ts
  src/hooks/queries/use-get-my-posts-query.ts
  src/hooks/queries/use-get-user-by-id-query.ts
  src/hooks/queries/use-get-user-posts-by-month-query.ts
  src/services/auth-service.ts
  src/services/friend-service.ts
  src/services/home-client-service.ts
  src/services/home-service.ts
  src/services/music-service.ts
  src/services/post-service.ts
  src/services/posting-service.ts
  src/services/supabase-client-service.ts
  src/services/supabase-server-service.ts
  src/services/user-service.ts
  src/types/common-components.types.ts
  src/types/components-props.type.ts
  src/types/img-component.type.ts
  src/types/posts.type.ts
  src/ui/common/button.common.tsx
  src/ui/common/emotion-image.common.tsx
  src/ui/common/input.common.tsx
  src/utils/home-emotion.util.ts
Labels: ⚙️ Setting, 🪫 도현, ✨ Feature

#55 [Feature/Home] 기능 구현 및 충돌 처리 #3
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-nopost.tsx
  src/app/music/components/emotion-based-playlists.tsx
  src/app/music/components/spotify-login.tsx
  src/app/page.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/constants/date-color.ts
  src/constants/emotions-url.constant.ts
  src/services/friend-service.ts
  src/services/home-client-service.ts
  src/services/home-service.ts
  src/services/post-service.ts
  src/services/user-service.ts
  src/ui/common/emotion-image.common.tsx
Labels: ⚙️ Setting, 🐰 선영, 🔨 Refactor, 🎨 CSS

#58 [Feature/List] 감정 통계 로직
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/page.tsx
  src/constants/emotion.constant.ts
  src/hooks/queries/use-get-my-posts-query.ts
  src/services/post-service.ts
  src/ui/common/emotion-graph.tsx
  src/ui/common/popup.tsx
  src/utils/emotion-graph-cal.util.ts
Labels: 🧸 주하, ✨ Feature

#62 [Feature/Homefriend] 홈 친구 부분 구현, css 다듬기 및 오류 수정 #3
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/constants/emotion.constant.ts
  src/constants/emotions-url.constant.ts
  src/hooks/queries/use-get-user-by-id-query.ts
  src/services/home-service.ts
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#63 [Feature/Homemusic] 스타일을 적용해뒀습니다. #3
  src/app/(home)/components/home-music.tsx
Labels: 🐰 선영, 🎨 CSS

#66 [Feature/m client] Spotify 플레이리스트 검색 기능 구현 및 UI 정리 #4
  src/app/(layout)/header.tsx
  src/app/(layout)/navigation.tsx
  src/app/api/spotify/callback/route.ts
  src/app/music/components/emotion-based-playlists.tsx
  src/app/music/components/spotify-login.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/query-keys.constant.ts
  src/constants/spotify.constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/services/music-service.ts
  src/utils/music-cookies.util.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#68 [Feature/Home] 헤더의 닉네임 오류 수정, css 다듬기 #3
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-zustand.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/constants/query-keys.constant.ts
  src/hooks/queries/use-get-user-nickname-by-id-query.ts
  src/hooks/zustand/store.ts
  src/services/home-client-service.ts
  src/services/home-service.ts
  src/types/zustand.type.ts
Labels: 🐞 BugFix, 🐰 선영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#69 [Feature/Home] 홈페이지 css 및 헤더 작업
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/type.ts
  src/app/(home)/types/HomeDate.ts
  src/app/page.tsx
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#72 [Feature/m client] 감정 기반 추천 및 북마크 기능 구현 #4
  src/app/api/spotify/callback/route.ts
  src/app/music/[id]/page.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-item.tsx
  src/app/music/_components/playlist-list.tsx
  src/app/music/_components/tab-buttons.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/music-constant.ts
  src/constants/toast-message.constant.ts
  src/services/music-bookmark-service.ts
  src/services/music-service.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#71 [Feature/Posting] 작성글 업로드 #8
  .vscode/settings.json
  src/app/posting/_components/posting-emotion-modal-button.tsx
  src/app/posting/_components/posting-emotion-modal.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-create-posts-mutation.ts
  src/hooks/mutations/use-post-emotion-mutation.ts
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
  src/services/post-service.ts
Labels: ✨ Feature, 🐋 현식

#73 [Feature/Text] 공통 텍스트 컴포넌트를 만들었습니다. #3
  src/types/text-component.type.ts
  src/ui/common/text.common.tsx
Labels: 🐰 선영, 🎨 CSS

#75 [Feature/Homepage] 회원가입 > 홈 헤더 설정 / 이름 리펙토링 / css 다듬기
  src/app/(home)/components/home-friend.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/services/home-client-service.ts
  src/services/home-service.ts
Labels: 🐞 BugFix, 🐰 선영, 🔨 Refactor, 🎨 CSS

#65 [Feature/userpage] 마이페이지 기초 UI 구성 / 닉네임 변경 로직 구현 / 마이페이지 내의 리스트 페이지 폴더 생성 및 라우팅 구현
  src/app/friends/components/friend-list.tsx
  src/app/friends/components/friend-request-button.tsx
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/components/friend-search-input.tsx
  src/app/friends/page.tsx
  src/app/friends/request/components/friend-request-received-friend-list.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/friends/request/page.tsx
  src/app/friends/type.ts
  src/app/my-page/components/mypage-menu-item.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/my-page/type.ts
  src/app/notice/page.tsx
  src/app/smookie-makers/page.tsx
  src/app/terms/page.tsx
  src/app/version/page.tsx
  src/constants/form-message.constant.ts
  src/constants/query-keys.constant.ts
  src/constants/toast-message.constant.ts
  src/constants/ui-text.ts
  src/hooks/mutations/use-accept-friend-request-mutation.ts
  src/hooks/mutations/use-delete-friend-mutation.ts
  src/hooks/mutations/use-send-friend-request-mutation.ts
  src/hooks/mutations/use-update-nickname-mutation.ts
  src/hooks/queries/use-get-my-friends-query.ts
  src/hooks/queries/use-get-received-requests-query.ts
  src/hooks/queries/use-get-sent-requests-query.ts
  src/hooks/queries/use-get-user-nickname-query.ts
  src/hooks/queries/use-search-user-query.ts
  src/services/auth-service.ts
  src/services/friend-request-service.ts
  src/services/my-friends-service.ts
  src/services/nickname-service.ts
  src/services/supabase-server-service.ts
  src/services/user-client-service.ts
  src/services/user-search-service.ts
  src/ui/lucide/.lucide.d.ts
Labels: 🪫 도현, ✨ Feature

#76 [Feature/List] 리스트 페이지 ui 작업
  public/images/fonts/PretendardVariable.woff2
  public/images/fonts/ownglyph.ttf
  src/app/fonts/PretendardVariable.woff2
  src/app/fonts/ownglyph.ttf
  src/app/globals.css
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/constants/emotion.constant.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/stores/post-date-store.ts
  src/types/posts.type.ts
  src/ui/common/emotion-graph.tsx
  tailwind.config.ts
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#77 [Feature/m client] Spotify 추천 플리 탭 / 즐겨찾기 탭 기능 구현 중
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-item.tsx
  src/app/music/_components/playlist-list.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/_components/tab-buttons.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/music-constant.ts
  src/constants/query-keys.constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/hooks/queries/use-get-all-bookmarked-playlists-by-id-query.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/services/music-bookmark-service.ts
Labels: 🐥 우영, ✨ Feature

#80 [Feature/List] ui 디테일 수정
  src/ui/common/emotion-graph.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#81 [Feature/m client] 충돌 가득 뮤테이션.. #4
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/services/music-bookmark-service.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature

#82 [Refactor] 처리 및 오류 핸들링 개선
  src/app/api/spotify/callback/route.ts
  src/app/friends/components/friend-list.tsx
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/page.tsx
  src/app/friends/request/components/friend-request-received-friend-list.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/list/_components/list-card.tsx
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
  src/constants/toast-message.constant.ts
  src/hooks/queries/use-get-all-bookmarked-playlists-by-id-query.ts
  src/hooks/queries/use-get-received-requests-query.ts
  src/hooks/queries/use-get-sent-requests-query.ts
  src/services/friend-request-service.ts
  src/services/music-bookmark-service.ts
  src/services/my-friends-service.ts
  src/services/nickname-service.ts
  src/services/user-client-service.ts
  src/services/user-search-service.ts
Labels: 🐞 BugFix, 🔨 Refactor

#83 refactor: 북마크 플레이리스트 처리 및 오류 핸들링 개선
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/services/music-bookmark-service.ts
Labels: 🐞 BugFix, 🔨 Refactor

#84 [Refactor] 북마크 관련 코드 정리 및 삭제 기능 개선
  src/app/list/_components/list-card.tsx
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
  src/app/posting/_components/posting-emotion-modal-slice.tsx
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/services/post-service.ts
  src/ui/common/emotion-graph.tsx
Labels: 🐞 BugFix, 🧸 주하, 🐰 선영, 🐥 우영, 🪫 도현, 🐋 현식

#89 [Feature/Homepage] 홈/ 네비/ 헤더 수정 #86 #3
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(layout)/navigation.tsx
  src/ui/common/emotion-image.common.tsx
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#87 [Style/Posting]: 게시글 폼의 텍스트 영역 스타일 및 레이아웃 개선
  src/app/posting/_components/posting-form.tsx
Labels: 🐋 현식, 🎨 CSS

#88 [Feature/List] 그래프 팝업 ui/ 기능 업데이트
  src/app/list/_components/list-card.tsx
  src/ui/common/emotion-graph.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#90 [Refactor/music] Music 페이지 기능 구현 완료
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/music-constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/hooks/queries/use-get-all-bookmarked-playlists-by-id-query.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/services/music-bookmark-service.ts
Labels: 🐥 우영, 🔨 Refactor

#91 [style/ sign-in,up] 기초 css #3
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/types/components-props.type.ts
  src/ui/common/button.common.tsx
Labels: 🐰 선영, 🎨 CSS

#96 [Feature/List] 팝업 css 수정
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/ui/common/emotion-graph.tsx
  tailwind.config.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#97 [Feature/List] 줄바꿈, 삭제/수정 기능 제대로
  src/app/list/_components/list-card.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#99 [Feature/Home] 헤더 상단 고정 및 리펙토링 #3
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/posting/_components/posting-form.tsx
Labels: 🐰 선영, 🔨 Refactor, 🎨 CSS

#101 [Design/music] Music 페이지 CSS 80% 완료 #4
  pnpm-lock.yaml
  src/app/list/_components/list-card-container.tsx
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
Labels: 🐥 우영, 🎨 CSS

#103 [Feature/Sign] 로그인, 회원가입 페이지 #10
  src/app/list/_components/list-card.tsx
  src/app/my-page/components/mypage-graph.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/posting/page.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-in/page.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/app/sign-up/page.tsx
  src/constants/toast-message.constant.ts
  src/hooks/mutations/auth-mutation.ts
  src/services/auth-service.ts
  src/services/friend-request-service.ts
  src/services/supabase-server-service.ts
  src/ui/common/input.common.tsx
  src/ui/common/mypage-emotion-graph.tsx
Labels: ✨ Feature, 🐋 현식, 🎨 CSS

#110 [Feature/Posting] 포스팅 포커스 수정
  .vscode/settings.json
  src/app/posting/_components/posting-form.tsx
  src/constants/query-keys.constant.ts
  src/hooks/queries/use-get-posts-by-postId-query.ts
  src/services/post-service.ts
Labels: ✨ Feature, 🐋 현식

#112 [Feature/List] 스크롤 기능 추가
  src/app/list/[id]/page.tsx
  src/app/list/_components/list-card-container.tsx
  src/hooks/queries/use-get-monthly-posts-query.ts
  src/hooks/zustand/post-date-store.ts
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature

#113 [Feature/Posting] 오늘 이미 포스팅된 경우, 추가 포스팅 제한 #8
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
  src/app/posting/page.tsx
  src/constants/query-keys.constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-create-posts-mutation.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/hooks/queries/use-get-posts-by-userId-and-today-query.ts
  src/services/post-service.ts
Labels: ✨ Feature, 🐋 현식

#114 Refactor/homepage 여러가지 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(layout)/navigation.tsx
  src/app/page.tsx
  src/app/posting/page.tsx
  src/constants/emotions-music.constant.ts
  src/hooks/queries/use-get-posts-today-emotion-by-id-query.ts
  src/services/post-service.ts
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#115 [Refactor/homepage] 공지, 약관 페이지 제작/ 홈 오류 수정 / 홈 뮤테이션 수정 #107
  src/app/(home)/components/home-music.tsx
  src/app/notice/page.tsx
  src/app/terms/page.tsx
  src/hooks/mutations/use-create-posts-mutation.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
  src/hooks/queries/use-get-user-posts-by-month-query.ts
Labels: 🐰 선영, 🔨 Refactor, ✨ Feature

#120 [Feature/List] css 스타일 변경
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#116 [Refactor/music] 일기 작성 여부에 따른 플리 추천 기능 및 UI 수정 #106
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/_components/tab-button.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/spotify.constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/services/music-bookmark-service.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#121 [Refactor/homepage] 달력, 친구 보더, 홈 음악 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/constants/emotions-music.constant.ts
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
  src/hooks/queries/use-get-posts-today-emotion-by-id-query.ts
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#123 [Refactor/music] Spotify 로그아웃 기능 추가 및 상수 정리 #106
  src/app/api/spotify/sign-out/route.ts
  src/constants/spotify.constant.ts
  src/services/auth-service.ts
Labels: 🐥 우영, 🔨 Refactor, ✨ Feature

#124 [Refactor/List] 쿼리키 통일 및 디자인 미세 조정
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(layout)/navigation.tsx
  src/app/friends/components/friend-list.tsx
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/components/friend-search-input.tsx
  src/app/friends/page.tsx
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/smookie-makers/page.tsx
  src/constants/tutorial.constant.ts
  src/hooks/mutations/use-accept-friend-request-mutation.ts
  src/hooks/mutations/use-cancel-friend-request-mutation.ts
  src/hooks/mutations/use-delete-friend-mutation.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/hooks/mutations/use-send-friend-request-mutation.ts
  src/hooks/mutations/use-update-nickname-mutation.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/hooks/queries/use-get-all-posts-query.ts
  src/hooks/queries/use-get-friend-posts-query.ts
  src/hooks/queries/use-get-monthly-posts-query.ts
  src/hooks/queries/use-get-my-posts-query.ts
  src/hooks/queries/use-get-received-requests-query.ts
  src/hooks/queries/use-get-user-nickname-by-id-query.ts
  src/hooks/zustand/list-tab-store.ts
  src/services/auth-service.ts
Labels: 🐞 BugFix, 🧸 주하, 🐰 선영, 🔨 Refactor, 🪫 도현, 🎨 CSS

#126 [Refactor] 음악 가져오는 기능 수정 및 디테일 수정
  src/app/friends/components/friend-request-button.tsx
  src/app/friends/page.tsx
  src/app/music/page.tsx
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/services/music-service.ts
Labels: 🐞 BugFix, 🧸 주하, 🔨 Refactor, 🎨 CSS

#127 [Refactor] 음악 레이아웃
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/page.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/smookie-makers/page.tsx
  src/app/terms/page.tsx
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#128 [Refactor/Tutorial] 튜토리얼 페이지 수정 #125
  public/images/home-tutorial.png
  public/images/list-tutorial.png
  public/images/list-tutorial2.png
  public/images/list-tutorial3.png
  public/images/music-tutorial.png
  public/images/music-tutorial2.png
  public/images/smookie-tutorial.png
  src/app/tutorial/_components/tutorial-description.tsx
  src/app/tutorial/page.tsx
  src/constants/tutorial.constant.ts
  tailwind.config.ts
Labels: ✨ Feature, 🐋 현식, 🎨 CSS

#129 [Refactor] 게시 버튼 반응형으로 변경
  .vscode/settings.json
  src/app/(home)/components/home-header.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/list/_components/list-card.tsx
  src/app/posting/_components/posting-form.tsx
  tailwind.config.ts
Labels: 🔨 Refactor, 🐋 현식, 🎨 CSS

#130 [Refactor/Tutorial] 컴포넌트의 여백 및 오버플로우 스타일 수정 #125
  src/app/tutorial/_components/tutorial-description.tsx
Labels: 🐋 현식, 🎨 CSS

#131 [Refactor/Tutorial] 튜토리얼 List 설명 페이지 수정 #125
  src/app/tutorial/_components/tutorial-description.tsx
  tailwind.config.ts
Labels: 🐋 현식, 🎨 CSS

#132 [Deploy] 배포
  src/app/tutorial/_components/tutorial-description.tsx
  tailwind.config.ts
Labels: 🌏 Deploy

#133 style: 홈 음악 및 재생 목록 카드 컴포넌트의 이미지 크기 및 여백 조정 #106
  src/app/(home)/components/home-music.tsx
  src/app/music/_components/playlist-card.tsx
Labels: 🐥 우영, 🎨 CSS

#139 [Bugfix/Posting] 수정할때 content가 잘못 불러와지는 버그 수정 #138
  src/app/posting/_components/posting-form.tsx
Labels: 🐞 BugFix, 🐋 현식

#141 [Feature] 공통 컴포넌트, 알림창
  src/app/list/_components/list-card-container.tsx
  src/constants/alert-message.ts
  src/ui/common/alert.tsx
Labels: 🧸 주하, ✨ Feature, 🎨 CSS

#142 [Bugfix/music] 스크롤 시, 이미지와 탭 고정 및 리팩토링
  src/app/(home)/components/home-music.tsx
  src/app/music/_components/bookmarked-playlists.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-content.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/recommend-playlists.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/constants/emotion-color.constant.ts
  src/constants/spotify.constant.ts
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-music-bookmarks-mutation.ts
  src/hooks/queries/use-get-all-bookmarked-playlists-by-id-query.ts
  src/hooks/queries/use-get-all-playlists-by-query-query.ts
  src/services/music-service.ts
Labels: 🐞 BugFix, 🐥 우영, 🔨 Refactor, 🎨 CSS

#145 [Style/home] 홈 페이지 반응형 작업, 내 게시글 데베 최신순으로 불러오게 수정 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/(home)/components/home-stack.tsx
  src/app/page.tsx
  src/hooks/mutations/use-delete-friend-mutation.ts
  src/services/post-service.ts
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#146 [Bugfix/music] font-bold 속성 -> strong 태그로 변경
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/services/music-service.ts
  src/types/text-component.type.ts
  src/ui/common/alert.tsx
  src/ui/common/emotion-graph.tsx
  src/ui/common/text.common.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#144 [Refactor/userpage] 튜토리얼 다시보기 추가
  src/app/globals.css
  src/app/layout.tsx
  src/app/my-page/components/mypage-graph.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/tutorial/_components/tutorial-container.tsx
  src/app/tutorial/page.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, 🪫 도현, ✨ Feature, 🎨 CSS

#148 [Style/common] 이미지 공통 컴포넌트, 네비바, 헤더 작업 중 #107
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
  src/ui/common/emotion-image.common.tsx
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#147 [Refactor/common] 로그인 및 회원가입 UI 수정
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/app/tutorial/_components/tutorial-container.tsx
  src/constants/tutorial.constant.ts
  src/ui/common/button.common.tsx
Labels: 🐥 우영, 🎨 CSS

#149 [refactor/common]: 루트 레이아웃, 헤더, 네비게이션 반응형 CSS 수정
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/navigation.tsx
  src/app/layout.tsx
Labels: 🐥 우영, 🎨 CSS

#143 [Refactor/Posting] 포스팅 페이지 수정 #117
  .vscode/settings.json
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/navigation.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-emotion-modal-button.tsx
  src/app/posting/_components/posting-emotion-modal.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/hooks/mutations/use-create-posts-mutation.ts
  src/hooks/mutations/use-remove-post-mutation.ts
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
  src/hooks/zustand/posting-store.ts
  src/types/zustand.type.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🐋 현식, 🎨 CSS

#150 [Style/Home] 홈 반응형 추가, 기타 작업 수정 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/page.tsx
  src/ui/common/emotion-image.common.tsx
Labels: 🐰 선영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#151 [Refactor/List] 디자인 수정 및 config 파일 수정
  src/app/friends/request/page.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/ui/common/mypage-emotion-graph.tsx
  tailwind.config.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#152 [Feature] 탭 컴포넌트
  package.json
  pnpm-lock.yaml
  src/app/(home)/components/home-friend.tsx
  src/app/(layout)/navigation.tsx
  src/app/friends/request/page.tsx
  src/app/list/_components/list-card-container.tsx
  src/hooks/zustand/list-tab-store.ts
  src/ui/common/tab.tsx
Labels: 🧸 주하, 🐰 선영, 🔨 Refactor, 🪫 도현, ✨ Feature, 🎨 CSS

#153 [Style/my] 마이페이지 반응형 CSS 1차 완료
  src/app/(home)/components/home-header.tsx
  src/app/(layout)/header-desk.tsx
  src/app/layout.tsx
  src/app/my-page/components/mypage-menu-item.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/ui/common/mypage-emotion-graph.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#156 [Refactor] 컴포넌트 추가 및 수정
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/request/page.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/constants/cookie-alert.constant.ts
  src/ui/common/alert.common.tsx
  src/ui/common/cookie-alert.common.tsx
  src/ui/common/emotion-graph.common.tsx
  src/ui/common/popup-bg.common.tsx
  src/ui/common/tab.common.tsx
  src/ui/common/tab.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#154 [Style/music] 뮤직페이지 반응형 CSS 1차 완료
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-content.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/page.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#159 [Feature] 버튼 컴포넌트, alert 컴포넌트
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/types/components-props.type.ts
  src/ui/common/alert.common.tsx
  src/ui/common/button.common.tsx
  src/ui/common/emotion-graph.common.tsx
  src/ui/common/mypage-emotion-graph.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#158 [Style/post]: PostingPage 반응형 CSS 수정
  src/app/(home)/components/home-header.tsx
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-button.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/constants/form-message.constant.ts
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#160 [Feature/Sign] 회원가입 페이지 비밀번호확인 추가 #155
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/app/sign-up/type.ts
  src/constants/validations.constant.ts
  src/hooks/mutations/auth-mutation.ts
  src/services/auth-service.ts
Labels: ✨ Feature, 🐋 현식

#162 [Refactor/List] 반응형 구현
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/ui/common/tab.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#163 [Style/home] 홈 반응형 및 쿠키알럿 수정 #107
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/(home)/components/home-stack.tsx
  src/app/page.tsx
  src/types/cookie-alert.type.ts
  src/ui/common/cookie-alert.common.tsx
Labels: 🐰 선영, 🔨 Refactor, 🎨 CSS

#164 [Style/sign]: 로그인 및 회원가입 페이지 반응형 수정
  src/app/(layout)/header-desk.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-in/page.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/app/sign-up/page.tsx
  src/ui/common/input.common.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#166 [Feature] 버튼, 알림창 컴포넌트
  src/app/list/_components/list-card.tsx
  src/constants/alert-message.ts
  src/ui/common/alert.common.tsx
  src/ui/common/button.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#167 [Feature/Sign] Protected Route, MiddleWare 설정
  .vscode/settings.json
  src/app/(home)/components/home-header.tsx
  src/app/friends/page.tsx
  src/app/list/page.tsx
  src/app/music/page.tsx
  src/app/my-page/page.tsx
  src/app/notice/page.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/smookie-makers/page.tsx
  src/app/terms/page.tsx
  src/middleware.ts
  src/services/middleware.ts
Labels: ✨ Feature, 🐋 현식

#165 [Feature] 레이아웃 및 리스트 페이지 css
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/main-content-container.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/ui/common/emotion-graph.common.tsx
  src/ui/common/input.common.tsx
  src/ui/common/tab.common.tsx
  tailwind.config.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#171 [Style/music] 뮤직페이지 반응형 css 수정 #135
  src/app/(layout)/main-content-container.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-content.tsx
  src/app/music/_components/playlist-tab-container.tsx
  src/app/music/_components/tab-button.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/services/supabase-server-service.ts
  src/ui/common/tab.common.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#169 [Style/home] 홈 반응형 및 자잘한 수정 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-header.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/friends/page.tsx
  src/app/page.tsx
  src/app/smookie-makers/page.tsx
Labels: 🐰 선영, 🔨 Refactor, ✨ Feature, 🎨 CSS

#170 [Refactor/userpage] 마이페이지 수정사항 수정
  public/images/friend-tutorial.png
  public/images/friend-tutorial2.png
  src/app/friends/page.tsx
  src/app/friends/request/components/friend-request-received-friend-list.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/friends/request/page.tsx
  src/app/my-page/components/mypage-menu-item.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/notice/page.tsx
  src/app/smookie-makers/page.tsx
  src/app/tutorial/_components/tutorial-container.tsx
  src/app/tutorial/_components/tutorial-description.tsx
  src/app/tutorial/page.tsx
  src/app/tutorial/type.ts
  src/constants/toast-message.constant.ts
  src/constants/tutorial.constant.ts
  src/services/nickname-service.ts
  src/ui/common/mypage-emotion-graph.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, 🪫 도현, ✨ Feature, 🎨 CSS

#176 [Feature] 레이아웃 수정
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/main-content-container.tsx
  src/constants/emotion.constant.ts
  src/ui/common/cookie-alert.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#177 [Style/home] 파비콘 수정, 홈 css 다듬기, 헤더 리펙토링 #107
  public/images/Fluffy.png
  public/images/fluffy.ico
  public/images/joy.ico
  public/images/joy.png
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-date.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/header-zustand.tsx
  src/app/(layout)/header.tsx
  src/app/layout.tsx
Labels: 🐰 선영, 🔨 Refactor, 🎨 CSS

#180 [Refactor/userpage] 내 친구 목록에서 그래프 팝업 구현 / 튜토리얼 페이지 이미지 변경
  public/images/friend-tutorial2.png
  public/images/home-tutorial.png
  public/images/list-tutorial.png
  public/images/list-tutorial3.png
  src/app/friends/components/friend-list.tsx
  src/app/friends/page.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/tutorial/_components/tutorial-description.tsx
Labels: 🪫 도현, ✨ Feature, 🎨 CSS

#179 [Feature/loading] 공통 로딩 컴포넌트 #174
  src/app/music/_components/playlist-content.tsx
  src/app/music/page.tsx
  src/ui/common/loading-cookie.common.tsx
Labels: 🐥 우영, ✨ Feature, 🎨 CSS

#182 [Feature] Polling 실시간
  src/hooks/polling/use-polling-query.ts
  src/hooks/queries/use-get-my-friends-query.ts
  src/hooks/queries/use-get-received-requests-query.ts
  src/services/friend-request-service.ts
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature

#183 [Style/home] 헤더 네비 홈 css 피드백 반영 및 네비 리펙토링 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/navigation.tsx
  src/app/tutorial/_components/tutorial-description.tsx
Labels: 🐰 선영, 🔨 Refactor, 🎨 CSS

#185 [Feature/list] 애니메이션 추가 및 컴포넌트 디자인 수정
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/constants/alert-message.ts
  src/ui/common/alert.common.tsx
  src/ui/common/button.common.tsx
  src/ui/common/emotion-graph.common.tsx
  src/ui/common/tab.common.tsx
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature, 🎨 CSS

#187 [Refactor/music] Music 페이지 CSS 애니메이션 추가 #135
  src/app/(layout)/main-content-container.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-content.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/ui/common/tab.common.tsx
Labels: 🐥 우영, 🔨 Refactor, 🎨 CSS

#186 [Refactor/userpage] 친구 요청이 있는 사용자에게 요청 시 수락 루트로 로직 변경 / CSS 전반적인 수정 / 친구 삭제 토스트 추가
  package.json
  pnpm-lock.yaml
  src/app/friends/components/friend-list.tsx
  src/app/friends/components/friend-request-button.tsx
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/components/friend-search-input.tsx
  src/app/friends/page.tsx
  src/app/friends/request/components/friend-request-received-friend-list.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/friends/request/page.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/notice/page.tsx
  src/app/smookie-makers/page.tsx
  src/app/terms/page.tsx
  src/constants/toast-message.constant.ts
  src/hooks/mutations/use-delete-friend-mutation.ts
Labels: 🪫 도현, ✨ Feature, 🎨 CSS

#189 [Feature/Error] 에러 페이지, 로딩 페이지
  src/app/error.tsx
  src/app/loading.tsx
Labels: 🧸 주하, ✨ Feature, 🎨 CSS

#188 [Feature/List] 반응형 디자인 및 애니메이션
  src/app/list/_components/conetent.tsx
  src/app/list/_components/list-card.tsx
  src/hooks/is-mobile/use-is-mobile.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#190 [Refactor/Posting] 포스팅 페이지 뒤로가기 알림 창 #117
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/navigation.tsx
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-button.tsx
  src/app/posting/_components/posting-emotion-modal-button.tsx
  src/app/posting/_components/posting-emotion-modal-loading.tsx
  src/app/posting/_components/posting-emotion-modal-slice.tsx
  src/app/posting/_components/posting-emotion-modal.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/hooks/zustand/posting-store.ts
  src/types/zustand.type.ts
Labels: 🔨 Refactor, ✨ Feature, 🐋 현식, 🎨 CSS

#191 [Style/home] 홈 스르륵 애니메이션, 리펙토링 및 호버 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/(home)/components/home-stack.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/navigation.tsx
Labels: 🐰 선영, 🔨 Refactor, 🎨 CSS

#193 [Style] 전체 css, 레이아웃 수정
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-stack.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/main-content-container.tsx
  src/app/friends/components/friend-list.tsx
  src/app/friends/components/friend-request-popup.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/list/_components/conetent.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/list-card.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/_components/playlist-content.tsx
  src/app/music/page.tsx
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/hooks/is-mobile/use-is-mobile.ts
  src/ui/common/ empty-alert.common.tsx
  src/ui/common/alert.common.tsx
  src/ui/common/button.common.tsx
  tailwind.config.ts
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS, 🌸 희원

#194 [Feature/footer] : Footer 컴포넌트 CSS 수정 #174
  src/ui/common/footer.common.tsx
  src/ui/svg-icon/github.icon.tsx
  src/ui/svg-icon/google.icon.tsx
  src/ui/svg-icon/spotify.icon.tsx
Labels: 🐥 우영, 🎨 CSS

#196 [Style/home] 애니메이션, 호버, 홈 커스텀 로딩 #107
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-loading.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(layout)/header-desk.tsx
  src/app/loading.tsx
  src/app/page.tsx
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#200 [Refactor/music]: Music 페이지 CSS 수정 #135
  src/app/music/_components/playlist-card.tsx
  src/app/music/_components/playlist-content.tsx
Labels: 🐥 우영, 🎨 CSS

#199 [Feature] 컴포넌트
  src/ui/common/alert.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🎨 CSS

#198 [Feature/List] 무한스크롤
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/navigation.tsx
  src/app/list/_components/list-card-container.tsx
  src/app/list/_components/my-posts-list.tsx
  src/hooks/queries/use-get-friend-posts-query.ts
  src/hooks/queries/use-infinite-user-posts-by-month-query.ts
  src/hooks/zustand/post-date-store.ts
Labels: 🧸 주하, 🔨 Refactor, ✨ Feature

#203 [Style/home] 홈 뮤직 애니메이션, 오타 리펙토링 #107
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/app/page.tsx
Labels: 🐰 선영, ✨ Feature, 🎨 CSS

#202 [Feature/Mypage] 애니메이션
  src/app/friends/components/friend-list.tsx
  src/app/globals.css
  src/app/my-page/components/mypage-container.tsx
  src/app/my-page/components/mypage-menu-list.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/my-page/page.tsx
  src/app/notice/_components/notice-container.tsx
  src/app/notice/page.tsx
Labels: 🐞 BugFix, 🧸 주하, ✨ Feature, 🎨 CSS

#205 [Feature/SignIn] 애니메이션
  src/app/list/_components/list-card.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/ui/common/footer-contents.tsx
  src/ui/common/footer.common.tsx
  src/ui/common/sign-button.common.tsx
Labels: 🧸 주하, 🪫 도현, 🎨 CSS

#204 [Refactor:Tutorial] 튜토리얼 확인 로직을 SignIn 페이지로 이동
  src/app/page.tsx
  src/app/sign-in/page.tsx
Labels: 🔨 Refactor, 🐋 현식

#201 [Refactor/Posting] 포스팅 페이지 리팩토링 및 공통 컴포넌트 일부 수정#117
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-button.tsx
  src/app/posting/_components/posting-emotion-modal-button.tsx
  src/app/posting/_components/posting-emotion-modal-loading.tsx
  src/app/posting/_components/posting-emotion-modal-slice.tsx
  src/app/posting/_components/posting-emotion-modal.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/posting/type.ts
  src/constants/form-message.constant.ts
  src/hooks/mutations/use-create-posts-mutation.ts
  src/hooks/mutations/use-update-posts-by-postId-mutation.ts
  src/ui/common/button.common.tsx
  src/ui/common/popup-bg.common.tsx
Labels: 🐞 BugFix, 🔨 Refactor, 🐋 현식

#208 [Feature/music] 디자인 수정
  src/app/music/_components/playlist-content.tsx
  src/app/music/page.tsx
  src/hooks/is-mobile/use-is-mobile.ts
  src/ui/common/tab.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🪫 도현, 🎨 CSS

#207 [Feature/PWA] PWA 설정
  .gitignore
  next.config.mjs
  src/app/manifest.ts
Labels: ✨ Feature, 🐋 현식

#210 [Refactor]: 일부 튜토리얼 css 수정
  src/app/tutorial/_components/tutorial-description.tsx
Labels: 🐥 우영, 🎨 CSS

#209 [CSS] 전체 애니메이션 수정
  src/app/(home)/components/home-calendar.tsx
  src/app/(home)/components/home-friend.tsx
  src/app/(home)/components/home-music.tsx
  src/app/(home)/components/home-posting.tsx
  src/app/(home)/components/home-stack.tsx
  src/app/(layout)/header-desk.tsx
  src/app/(layout)/header-mobile.tsx
  src/app/(layout)/main-content-container.tsx
  src/app/friends/components/friend-list.tsx
  src/app/friends/request/components/friend-request-received-friend-list.tsx
  src/app/friends/request/components/friend-request-sent-friend-list.tsx
  src/app/list/_components/conetent.tsx
  src/app/list/_components/list-card.tsx
  src/app/loading.tsx
  src/app/music/_components/emotion-select.tsx
  src/app/music/page.tsx
  src/app/music/type.ts
  src/app/my-page/components/mypage-menu-item.tsx
  src/app/my-page/components/mypage-profile.tsx
  src/app/posting/[id]/page.tsx
  src/app/posting/_components/posting-form.tsx
  src/app/posting/page.tsx
  src/app/sign-in/_components/sign-in-form.tsx
  src/app/sign-up/_components/sign-up-form.tsx
  src/types/img-component.type.ts
  src/ui/common/alert.common.tsx
  src/ui/common/emotion-graph.common.tsx
  src/ui/common/emotion-image.common.tsx
  src/ui/common/sign-button.common.tsx
  src/ui/common/tab.common.tsx
Labels: 🧸 주하, 🔨 Refactor, 🪫 도현, 🎨 CSS

#211 [Refactor/Tutorial] 튜토리얼 슬라이드 추가 #125
  package.json
  pnpm-lock.yaml
  src/app/tutorial/_components/tutorial-container.tsx
  src/app/tutorial/_components/tutorial-description.tsx
  src/app/tutorial/type.ts
  src/constants/tutorial.constant.ts
Labels: ✨ Feature, 🐋 현식
